name: shiyuan
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  provider: ^3.0.0
  cupertino_icons: any
  flutter_screenutil: any
  bot_toast: 3.0.0
  flutter_swiper : any
  dio: any
  dio_flutter_transformer: ^3.0.2
  shared_preferences: 0.5.7
  connectivity: any
  cached_network_image: any
  flutter_staggered_grid_view: any
  image_picker: 0.6.7
  chewie: 0.9.10
  video_player: 0.10.11+1
  qrcode: 1.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  assets:
    - imgs/login/denglu.png
    - imgs/login/mima.png
    - imgs/login/phone.png
    - imgs/login/code.png
    - imgs/login/close.png
    - imgs/login/open.png
    - imgs/login/sanjiao.png
    - imgs/login/select.png
    - imgs/login/select_de.png
    - imgs/login/top.png
    - imgs/nav/back.png
    - imgs/nav/sao.png
    - imgs/nav/xian.png
    - imgs/nav/LaunchImage.png
    - imgs/nav/empty.png
    - imgs/tabbar/daiban.png
    - imgs/tabbar/daiban_se.png
    - imgs/tabbar/shouye.png
    - imgs/tabbar/shouye_se.png
    - imgs/tabbar/shujuzhongxin.png
    - imgs/tabbar/shujuzhongxin_se.png
    - imgs/tabbar/wode.png
    - imgs/tabbar/wode_se.png
    - imgs/tabbar/xiaoxi.png
    - imgs/tabbar/xiaoxi_se.png
    - imgs/home/banner.png
    - imgs/home/yinhuanfaqi.png
    - imgs/home/xianshangpeixun.png
    - imgs/home/jihuajiancha.png
    - imgs/home/xianxiapeixun.png
    - imgs/home/yinhuanzhenggai.png
    - imgs/home/zuoyeguanli.png
    - imgs/home/gonggao.png
    - imgs/home/zaixiankaoshi.png
    - imgs/home/waibujiaoyu.png
    - imgs/home/falvbiaozhunku.png
    - imgs/home/xiangguanfanganquangongzuo.png
    - imgs/home/zuoyeguanli2.png
    - imgs/home/yinhuanfaqi2.png
    - imgs/home/xianshangpeixun2.png
    - imgs/home/jihuajiancha2.png
    - imgs/home/xianxiapeixun2.png
    - imgs/home/yinhuanzhenggai2.png
    - imgs/home/anquanhuiwu.png
    - imgs/home/kaoshidangan.png
    - imgs/home/yinhuanfaqi/xinzengyinhuan.png
    - imgs/home/yinhuanfaqi/delete.png
    - imgs/home/yinhuanfaqi/add.png
    - imgs/home/yinhuanfaqi/add2.png
    - imgs/home/xianshangpeixun/wrong.png
    - imgs/home/xianshangpeixun/right.png
    - imgs/home/xianshangpeixun/rightbutton.png
    - imgs/home/xianshangpeixun/leftbutton.png
    - imgs/home/xianshangpeixun/file.png
    - imgs/home/xianshangpeixun/video.png
    - imgs/home/jihua/jianchabiaozhun.png
    - imgs/home/jihua/drop.png
    - imgs/home/jihua/building.png
    - imgs/home/xianxia/scan.png
    - imgs/home/xianxia/signtop.png
    - imgs/home/xianxia/sign.png
    - imgs/home/xianxia/signsuccess.png
    - imgs/home/xianxia/peixunjilu.png
    - imgs/home/yinhuan/liuchengjinzhan.png
    - imgs/home/homework/denggaozuoye.png
    - imgs/home/homework/donghuozuoye.png
    - imgs/home/homework/lingxinggongcheng.png
    - imgs/home/homework/linshiyongdian.png
    - imgs/home/homework/youxiankongjian.png
    - imgs/home/homework/tianjiazhaopian.png
    - imgs/library/yueduleiji.png
    - imgs/library/tongbishangyue.png
    - imgs/library/yiwancheng.png
    - imgs/library/daizhixing.png
    - imgs/library/yueduleiji2.png
    - imgs/library/tongbishangyue2.png
    - imgs/library/yiwancheng2.png
    - imgs/library/daizhixing2.png
    - imgs/library/yinhuantiaoshu.png
    - imgs/library/yizhenggai.png
    - imgs/library/daizhenggai.png
    - imgs/library/weizhenggai.png
    - imgs/library/zhenggailv.png
    - imgs/library/jiangpai.png
    - imgs/library/UP.png
    - imgs/library/UP2.png
    - imgs/library/down.png
    - imgs/library/down2.png
    - imgs/message/xiaoxi1.png
    - imgs/message/xiaoxi2.png
    - imgs/message/xiaoxi3.png
    - imgs/mine/bg2.png
    - imgs/mine/dangqianbanben.png
    - imgs/mine/tuichudenglu.png
    - imgs/mine/xiugaimima.png
    - imgs/mine/right_icon.png
    - imgs/icon/search.png
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
